FROM nirmata/tomcat8-custom
MAINTAINER Nirmata "support@nirmata.com"

ENV JAVA_OPTS  -Dport.http.nonssl=80

RUN chmod 755 /usr/local/bin/run
ADD microservice.war /opt/tomcat/webapps/
RUN chmod 755 /opt/tomcat/webapps/microservice.war

EXPOSE 8080

CMD /usr/local/bin/run